# Generated by Django 4.2.10 on 2024-02-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
                ("mobileNo", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("colgStu", models.CharField(max_length=200)),
                ("exam", models.CharField(max_length=200)),
                ("feedback", models.CharField(max_length=500)),
            ],
        ),
    ]
