# Generated by Django 4.2.10 on 2024-02-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insti_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instimodel",
            name="website",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
