# Generated by Django 4.2.10 on 2024-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insti_app", "0002_instimodel_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
                ("mobileNo", models.CharField(max_length=200)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
    ]
