# Generated by Django 4.2.10 on 2024-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insti_app", "0003_contactmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("coaching", models.CharField(max_length=200)),
                ("year_of_study", models.CharField(max_length=20)),
            ],
        ),
    ]
