# Generated by Django 4.2.10 on 2024-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insti_app", "0004_mentorreg"),
    ]

    operations = [
        migrations.AddField(
            model_name="instimodel",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentorreg",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
