# Generated by Django 4.2.10 on 2024-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insti_app", "0005_instimodel_verified_mentorreg_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=100)),
                ("payment_id", models.CharField(max_length=100)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
