# Generated by Django 4.2.10 on 2024-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("timeslot", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
