# Generated by Django 4.2.10 on 2024-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_bookmodel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
