# Generated by Django 4.2.10 on 2024-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_bookmodel_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="order_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
