# Generated by Django 4.2.10 on 2024-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_bookmodel_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="meet_link",
            field=models.CharField(default="", max_length=100),
        ),
    ]
